// flashcards.js
export const flashcards = [
  { id: 1, question: "What is the capital of France?", answer: "Paris" },
  { id: 2, question: "What does HTML stand for?", answer: "HyperText Markup Language" },
  { id: 3, question: "What is 7 x 8?", answer: "56" },
  { id: 4, question: "What does CSS stand for?", answer: "Cascading Style Sheets" },
  { id: 5, question: "Which planet is known as the Red Planet?", answer: "Mars" },
  { id: 6, question: "What is the boiling point of water?", answer: "100°C or 212°F" },
  { id: 7, question: "What programming language is used to style websites?", answer: "CSS" },
  { id: 8, question: "What does JS stand for?", answer: "JavaScript" },
  { id: 9, question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci" },
  { id: 10, question: "What is React?", answer: "A JavaScript library for building UIs" },
  { id: 11, question: "What is the smallest prime number?", answer: "2" },
  { id: 12, question: "Who wrote 'Romeo and Juliet'?", answer: "William Shakespeare" },
  { id: 13, question: "What is the speed of light?", answer: "299,792,458 meters per second" },
  { id: 14, question: "Which language is used for backend development in Node.js?", answer: "JavaScript" },
  { id: 15, question: "What is the value of Pi (approx)?", answer: "3.14159" },
  { id: 16, question: "Which tag is used for a link in HTML?", answer: "<a>" },
  { id: 17, question: "Which country is known as the Land of the Rising Sun?", answer: "Japan" },
  { id: 18, question: "What does API stand for?", answer: "Application Programming Interface" },
  { id: 19, question: "What is the freezing point of water?", answer: "0°C or 32°F" },
  { id: 20, question: "What is JSX in React?", answer: "JavaScript XML" },
  { id: 21, question: "What is a component in React?", answer: "Reusable piece of UI" },
  { id: 22, question: "What keyword is used to define a constant in JS?", answer: "const" },
  { id: 23, question: "Which HTML tag is used for images?", answer: "<img>" },
  { id: 24, question: "What color is a banana?", answer: "Yellow" },
  { id: 25, question: "How do you declare a variable in JS?", answer: "Using var, let, or const" }
];
